import { PersonaData } from '@/data/personas';

interface Props {
  data: PersonaData;
}

const TrustFooter = ({ data }: Props) => {
  return (
    <div className="space-y-6 pb-12">
      <div className="bg-card rounded-xl border border-border p-6">
        <h2 className="text-lg font-semibold text-foreground mb-4">📊 Co-Pilot Accuracy — Last 90 Days</h2>
        <div className="grid grid-cols-3 gap-6">
          <div>
            <p className="text-sm font-medium text-foreground">Categorization</p>
            <p className="text-sm text-muted-foreground">{data.categorizationAccuracy}</p>
          </div>
          <div>
            <p className="text-sm font-medium text-foreground">Income prediction</p>
            <p className="text-sm text-muted-foreground">{data.incomePrediction}</p>
          </div>
          <div>
            <p className="text-sm font-medium text-foreground">Missed obligations</p>
            <p className="text-sm text-muted-foreground">{data.missedObligations}</p>
          </div>
        </div>
      </div>

      <p className="text-xs text-muted-foreground text-center max-w-3xl mx-auto">
        This prototype demonstrates Wealthsimple Hive, an AI financial co-pilot. In production, data flows via Open Banking APIs (Consumer-Driven Banking Act, 2026) and Wealthsimple's internal account data. AI categorization and recommendations are generated by a fine-tuned model. Human confirmation is required for all money movement. This is not financial advice.
      </p>
    </div>
  );
};

export default TrustFooter;
